### ISSUE TITLE
Prime algorithm

### ISSUE THREAD

**Issue by maasencioh** [mljs/hash-table#1]
Hello, which is the algorithm for the prime numbers?

**Comment by targos** [comment]
Hello, the prime number list is hardcoded. It has been generated so that if you take any prime in the list and multiply it by 2, you will find the next closest prime. Also if you ask for a specific capacity, you will get a very close prime number (within 1-2%). See https://github.com/carlsonp/Colt/blob/master/src/cern/colt/map/PrimeFinder.java#L25-L50 for more details.
